#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🚀 Chatty Web Architect Backend Setup');
console.log('=====================================\n');

function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer);
    });
  });
}

async function setup() {
  try {
    console.log('This setup will help you configure your backend environment.\n');

    // Check if .env already exists
    if (fs.existsSync('.env')) {
      const overwrite = await askQuestion('.env file already exists. Overwrite? (y/N): ');
      if (overwrite.toLowerCase() !== 'y') {
        console.log('Setup cancelled.');
        rl.close();
        return;
      }
    }

    console.log('Please provide the following configuration values:\n');

    const config = {};

    config.PORT = await askQuestion('Server port (default: 3001): ') || '3001';
    config.NODE_ENV = await askQuestion('Environment (development/production) [development]: ') || 'development';
    
    console.log('\n📊 Database Configuration:');
config.DB_HOST = await askQuestion('Database Host [localhost]: ') || 'localhost';
config.DB_PORT = await askQuestion('Database Port [5432]: ') || '5432';
config.DB_NAME = await askQuestion('Database Name [chatty_web_architect]: ') || 'chatty_web_architect';
config.DB_USER = await askQuestion('Database User [postgres]: ') || 'postgres';
config.DB_PASSWORD = await askQuestion('Database Password [password]: ') || 'password';
config.DB_SSL = await askQuestion('Use SSL for database connection? (y/N): ');
config.DB_SSL = config.DB_SSL.toLowerCase() === 'y' ? 'true' : 'false';

    console.log('\n🤖 OpenAI Configuration:');
    config.OPENAI_API_KEY = await askQuestion('OpenAI API Key: ');

    console.log('\n🔐 Security Configuration:');
    config.JWT_SECRET = await askQuestion('JWT Secret (leave empty to generate): ') || generateRandomString(64);

    console.log('\n💳 Payment Configuration (optional):');
    config.STRIPE_SECRET_KEY = await askQuestion('Stripe Secret Key (optional): ');
    config.STRIPE_WEBHOOK_SECRET = await askQuestion('Stripe Webhook Secret (optional): ');

    console.log('\n🌐 CORS Configuration:');
    config.CORS_ORIGIN = await askQuestion('CORS Origins (comma-separated) [http://localhost:8080]: ') || 'http://localhost:8080';

    console.log('\n⚡ Rate Limiting:');
    config.RATE_LIMIT_WINDOW = await askQuestion('Rate limit window (minutes) [15]: ') || '15';
    config.RATE_LIMIT_MAX_REQUESTS = await askQuestion('Max requests per window [100]: ') || '100';

    // Create .env file
    let envContent = '# Chatty Web Architect Backend Configuration\n';
    envContent += '# Generated by setup script\n\n';
    
    envContent += '# Server Configuration\n';
    envContent += `PORT=${config.PORT}\n`;
    envContent += `NODE_ENV=${config.NODE_ENV}\n\n`;
    
    envContent += '# Database Configuration\n';
envContent += `DB_HOST=${config.DB_HOST}\n`;
envContent += `DB_PORT=${config.DB_PORT}\n`;
envContent += `DB_NAME=${config.DB_NAME}\n`;
envContent += `DB_USER=${config.DB_USER}\n`;
envContent += `DB_PASSWORD=${config.DB_PASSWORD}\n`;
envContent += `DB_SSL=${config.DB_SSL}\n\n`;
    
    envContent += '# OpenAI Configuration\n';
    envContent += `OPENAI_API_KEY=${config.OPENAI_API_KEY}\n\n`;
    
    envContent += '# JWT Configuration\n';
    envContent += `JWT_SECRET=${config.JWT_SECRET}\n`;
    envContent += 'JWT_EXPIRES_IN=7d\n\n';
    
    if (config.STRIPE_SECRET_KEY || config.STRIPE_WEBHOOK_SECRET) {
      envContent += '# Stripe Configuration\n';
      if (config.STRIPE_SECRET_KEY) {
        envContent += `STRIPE_SECRET_KEY=${config.STRIPE_SECRET_KEY}\n`;
      }
      if (config.STRIPE_WEBHOOK_SECRET) {
        envContent += `STRIPE_WEBHOOK_SECRET=${config.STRIPE_WEBHOOK_SECRET}\n`;
      }
      envContent += '\n';
    }
    
    envContent += '# Rate Limiting\n';
    envContent += `RATE_LIMIT_WINDOW=${config.RATE_LIMIT_WINDOW}\n`;
    envContent += `RATE_LIMIT_MAX_REQUESTS=${config.RATE_LIMIT_MAX_REQUESTS}\n\n`;
    
    envContent += '# CORS\n';
    envContent += `CORS_ORIGIN=${config.CORS_ORIGIN}\n\n`;
    
    envContent += '# File Upload\n';
    envContent += 'MAX_FILE_SIZE=10485760\n';
    envContent += 'UPLOAD_PATH=./uploads\n';

    fs.writeFileSync('.env', envContent);

    console.log('\n✅ Configuration saved to .env file!');
    console.log('\n📋 Next steps:');
    console.log('1. Install dependencies: npm install');
    console.log('2. Run database migrations: npm run migrate');
    console.log('3. Start the server: npm run dev');
    console.log('\n🎉 Setup complete! Happy coding!');

  } catch (error) {
    console.error('❌ Setup failed:', error.message);
  } finally {
    rl.close();
  }
}

function generateRandomString(length) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

setup();
